dist: trusty
sudo: required
before_script:
    - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
    - sudo apt-get update -qq
    - sudo apt-get install --force-yes emacs-snapshot emacs-snapshot-el texinfo

    - emacs --version
install:
    - sudo apt-get install python-pygments realpath 
script: bash ./deploy.sh
env:
    global:
        - COMMIT_AUTHOR_EMAIL: "robin.ole.heinemann@t-online.de"
language: generic
